// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/agent/agent.proto

package agentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	agent "github.com/chinese-room-solutions/mass/rpc/agent"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentHubName is the fully-qualified name of the AgentHub service.
	AgentHubName = "mass.v1.agent.AgentHub"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentHubConnectProcedure is the fully-qualified name of the AgentHub's Connect RPC.
	AgentHubConnectProcedure = "/mass.v1.agent.AgentHub/Connect"
)

// AgentHubClient is a client for the mass.v1.agent.AgentHub service.
type AgentHubClient interface {
	// Connect establishes a persistent bidirectional stream between an agent
	// and MASS. The agent must send a Register message first, then listens
	// for jobs and sends results.
	Connect(context.Context) *connect.BidiStreamForClient[agent.AgentMessage, agent.HubMessage]
}

// NewAgentHubClient constructs a client for the mass.v1.agent.AgentHub service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentHubClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentHubClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentHubMethods := agent.File_rpc_agent_agent_proto.Services().ByName("AgentHub").Methods()
	return &agentHubClient{
		connect: connect.NewClient[agent.AgentMessage, agent.HubMessage](
			httpClient,
			baseURL+AgentHubConnectProcedure,
			connect.WithSchema(agentHubMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentHubClient implements AgentHubClient.
type agentHubClient struct {
	connect *connect.Client[agent.AgentMessage, agent.HubMessage]
}

// Connect calls mass.v1.agent.AgentHub.Connect.
func (c *agentHubClient) Connect(ctx context.Context) *connect.BidiStreamForClient[agent.AgentMessage, agent.HubMessage] {
	return c.connect.CallBidiStream(ctx)
}

// AgentHubHandler is an implementation of the mass.v1.agent.AgentHub service.
type AgentHubHandler interface {
	// Connect establishes a persistent bidirectional stream between an agent
	// and MASS. The agent must send a Register message first, then listens
	// for jobs and sends results.
	Connect(context.Context, *connect.BidiStream[agent.AgentMessage, agent.HubMessage]) error
}

// NewAgentHubHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentHubHandler(svc AgentHubHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentHubMethods := agent.File_rpc_agent_agent_proto.Services().ByName("AgentHub").Methods()
	agentHubConnectHandler := connect.NewBidiStreamHandler(
		AgentHubConnectProcedure,
		svc.Connect,
		connect.WithSchema(agentHubMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mass.v1.agent.AgentHub/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentHubConnectProcedure:
			agentHubConnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentHubHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentHubHandler struct{}

func (UnimplementedAgentHubHandler) Connect(context.Context, *connect.BidiStream[agent.AgentMessage, agent.HubMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.agent.AgentHub.Connect is not implemented"))
}
