// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/agent/agent.proto

package agent

import (
	rpc "github.com/chinese-room-solutions/mass/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_JobResult
	//	*AgentMessage_Heartbeat
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_rpc_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetRegister() *AgentRegister {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetJobResult() *AgentJobResult {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Register struct {
	Register *AgentRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_JobResult struct {
	JobResult *AgentJobResult `protobuf:"bytes,2,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Msg() {}

func (*AgentMessage_JobResult) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

type AgentRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Devices       []*AgentDevice         `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegister) Reset() {
	*x = AgentRegister{}
	mi := &file_rpc_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegister) ProtoMessage() {}

func (x *AgentRegister) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegister.ProtoReflect.Descriptor instead.
func (*AgentRegister) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRegister) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRegister) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentRegister) GetDevices() []*AgentDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceStats   []*AgentDeviceStats    `protobuf:"bytes,1,rep,name=device_stats,json=deviceStats,proto3" json:"device_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_rpc_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetDeviceStats() []*AgentDeviceStats {
	if x != nil {
		return x.DeviceStats
	}
	return nil
}

type AgentDeviceStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UsedMemoryMb   int32                  `protobuf:"varint,2,opt,name=used_memory_mb,json=usedMemoryMb,proto3" json:"used_memory_mb,omitempty"`
	TotalMemoryMb  int32                  `protobuf:"varint,3,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	UtilizationPct float64                `protobuf:"fixed64,4,opt,name=utilization_pct,json=utilizationPct,proto3" json:"utilization_pct,omitempty"` // 0-100, compute utilization
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentDeviceStats) Reset() {
	*x = AgentDeviceStats{}
	mi := &file_rpc_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDeviceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDeviceStats) ProtoMessage() {}

func (x *AgentDeviceStats) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDeviceStats.ProtoReflect.Descriptor instead.
func (*AgentDeviceStats) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentDeviceStats) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentDeviceStats) GetUsedMemoryMb() int32 {
	if x != nil {
		return x.UsedMemoryMb
	}
	return 0
}

func (x *AgentDeviceStats) GetTotalMemoryMb() int32 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *AgentDeviceStats) GetUtilizationPct() float64 {
	if x != nil {
		return x.UtilizationPct
	}
	return 0
}

type AgentJobResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*AgentJobResult_LoadModel
	//	*AgentJobResult_UnloadModel
	//	*AgentJobResult_ChatCompletion
	//	*AgentJobResult_Embedding
	//	*AgentJobResult_BatchEmbedding
	//	*AgentJobResult_Tokenize
	//	*AgentJobResult_Benchmark
	//	*AgentJobResult_Error
	Result        isAgentJobResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentJobResult) Reset() {
	*x = AgentJobResult{}
	mi := &file_rpc_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentJobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentJobResult) ProtoMessage() {}

func (x *AgentJobResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentJobResult.ProtoReflect.Descriptor instead.
func (*AgentJobResult) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentJobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AgentJobResult) GetResult() isAgentJobResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentJobResult) GetLoadModel() *AgentLoadModelResult {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_LoadModel); ok {
			return x.LoadModel
		}
	}
	return nil
}

func (x *AgentJobResult) GetUnloadModel() *AgentUnloadResult {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_UnloadModel); ok {
			return x.UnloadModel
		}
	}
	return nil
}

func (x *AgentJobResult) GetChatCompletion() *rpc.ChatCompletionResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_ChatCompletion); ok {
			return x.ChatCompletion
		}
	}
	return nil
}

func (x *AgentJobResult) GetEmbedding() *rpc.EmbeddingResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_Embedding); ok {
			return x.Embedding
		}
	}
	return nil
}

func (x *AgentJobResult) GetBatchEmbedding() *rpc.BatchEmbeddingResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_BatchEmbedding); ok {
			return x.BatchEmbedding
		}
	}
	return nil
}

func (x *AgentJobResult) GetTokenize() *rpc.TokenizeResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_Tokenize); ok {
			return x.Tokenize
		}
	}
	return nil
}

func (x *AgentJobResult) GetBenchmark() *AgentBenchmarkResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_Benchmark); ok {
			return x.Benchmark
		}
	}
	return nil
}

func (x *AgentJobResult) GetError() *AgentJobError {
	if x != nil {
		if x, ok := x.Result.(*AgentJobResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAgentJobResult_Result interface {
	isAgentJobResult_Result()
}

type AgentJobResult_LoadModel struct {
	LoadModel *AgentLoadModelResult `protobuf:"bytes,2,opt,name=load_model,json=loadModel,proto3,oneof"`
}

type AgentJobResult_UnloadModel struct {
	UnloadModel *AgentUnloadResult `protobuf:"bytes,3,opt,name=unload_model,json=unloadModel,proto3,oneof"`
}

type AgentJobResult_ChatCompletion struct {
	ChatCompletion *rpc.ChatCompletionResponse `protobuf:"bytes,4,opt,name=chat_completion,json=chatCompletion,proto3,oneof"`
}

type AgentJobResult_Embedding struct {
	Embedding *rpc.EmbeddingResponse `protobuf:"bytes,5,opt,name=embedding,proto3,oneof"`
}

type AgentJobResult_BatchEmbedding struct {
	BatchEmbedding *rpc.BatchEmbeddingResponse `protobuf:"bytes,6,opt,name=batch_embedding,json=batchEmbedding,proto3,oneof"`
}

type AgentJobResult_Tokenize struct {
	Tokenize *rpc.TokenizeResponse `protobuf:"bytes,7,opt,name=tokenize,proto3,oneof"`
}

type AgentJobResult_Benchmark struct {
	Benchmark *AgentBenchmarkResponse `protobuf:"bytes,8,opt,name=benchmark,proto3,oneof"`
}

type AgentJobResult_Error struct {
	Error *AgentJobError `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

func (*AgentJobResult_LoadModel) isAgentJobResult_Result() {}

func (*AgentJobResult_UnloadModel) isAgentJobResult_Result() {}

func (*AgentJobResult_ChatCompletion) isAgentJobResult_Result() {}

func (*AgentJobResult_Embedding) isAgentJobResult_Result() {}

func (*AgentJobResult_BatchEmbedding) isAgentJobResult_Result() {}

func (*AgentJobResult_Tokenize) isAgentJobResult_Result() {}

func (*AgentJobResult_Benchmark) isAgentJobResult_Result() {}

func (*AgentJobResult_Error) isAgentJobResult_Result() {}

type AgentLoadModelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentLoadModelResult) Reset() {
	*x = AgentLoadModelResult{}
	mi := &file_rpc_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLoadModelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLoadModelResult) ProtoMessage() {}

func (x *AgentLoadModelResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLoadModelResult.ProtoReflect.Descriptor instead.
func (*AgentLoadModelResult) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentLoadModelResult) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type AgentUnloadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUnloadResult) Reset() {
	*x = AgentUnloadResult{}
	mi := &file_rpc_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUnloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUnloadResult) ProtoMessage() {}

func (x *AgentUnloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUnloadResult.ProtoReflect.Descriptor instead.
func (*AgentUnloadResult) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{6}
}

type AgentJobError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentJobError) Reset() {
	*x = AgentJobError{}
	mi := &file_rpc_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentJobError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentJobError) ProtoMessage() {}

func (x *AgentJobError) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentJobError.ProtoReflect.Descriptor instead.
func (*AgentJobError) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentJobError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HubMessage_LoadChatModel
	//	*HubMessage_LoadEmbeddingModel
	//	*HubMessage_UnloadModel
	//	*HubMessage_ChatCompletion
	//	*HubMessage_Embedding
	//	*HubMessage_BatchEmbedding
	//	*HubMessage_Tokenize
	//	*HubMessage_Benchmark
	Msg           isHubMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_rpc_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HubMessage) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HubMessage) GetMsg() isHubMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HubMessage) GetLoadChatModel() *HubLoadChatModel {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_LoadChatModel); ok {
			return x.LoadChatModel
		}
	}
	return nil
}

func (x *HubMessage) GetLoadEmbeddingModel() *HubLoadEmbeddingModel {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_LoadEmbeddingModel); ok {
			return x.LoadEmbeddingModel
		}
	}
	return nil
}

func (x *HubMessage) GetUnloadModel() *HubUnloadModel {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_UnloadModel); ok {
			return x.UnloadModel
		}
	}
	return nil
}

func (x *HubMessage) GetChatCompletion() *HubChatCompletion {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_ChatCompletion); ok {
			return x.ChatCompletion
		}
	}
	return nil
}

func (x *HubMessage) GetEmbedding() *HubEmbedding {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_Embedding); ok {
			return x.Embedding
		}
	}
	return nil
}

func (x *HubMessage) GetBatchEmbedding() *HubBatchEmbedding {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_BatchEmbedding); ok {
			return x.BatchEmbedding
		}
	}
	return nil
}

func (x *HubMessage) GetTokenize() *HubTokenize {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_Tokenize); ok {
			return x.Tokenize
		}
	}
	return nil
}

func (x *HubMessage) GetBenchmark() *HubBenchmark {
	if x != nil {
		if x, ok := x.Msg.(*HubMessage_Benchmark); ok {
			return x.Benchmark
		}
	}
	return nil
}

type isHubMessage_Msg interface {
	isHubMessage_Msg()
}

type HubMessage_LoadChatModel struct {
	LoadChatModel *HubLoadChatModel `protobuf:"bytes,2,opt,name=load_chat_model,json=loadChatModel,proto3,oneof"`
}

type HubMessage_LoadEmbeddingModel struct {
	LoadEmbeddingModel *HubLoadEmbeddingModel `protobuf:"bytes,3,opt,name=load_embedding_model,json=loadEmbeddingModel,proto3,oneof"`
}

type HubMessage_UnloadModel struct {
	UnloadModel *HubUnloadModel `protobuf:"bytes,4,opt,name=unload_model,json=unloadModel,proto3,oneof"`
}

type HubMessage_ChatCompletion struct {
	ChatCompletion *HubChatCompletion `protobuf:"bytes,5,opt,name=chat_completion,json=chatCompletion,proto3,oneof"`
}

type HubMessage_Embedding struct {
	Embedding *HubEmbedding `protobuf:"bytes,6,opt,name=embedding,proto3,oneof"`
}

type HubMessage_BatchEmbedding struct {
	BatchEmbedding *HubBatchEmbedding `protobuf:"bytes,7,opt,name=batch_embedding,json=batchEmbedding,proto3,oneof"`
}

type HubMessage_Tokenize struct {
	Tokenize *HubTokenize `protobuf:"bytes,8,opt,name=tokenize,proto3,oneof"`
}

type HubMessage_Benchmark struct {
	Benchmark *HubBenchmark `protobuf:"bytes,9,opt,name=benchmark,proto3,oneof"`
}

func (*HubMessage_LoadChatModel) isHubMessage_Msg() {}

func (*HubMessage_LoadEmbeddingModel) isHubMessage_Msg() {}

func (*HubMessage_UnloadModel) isHubMessage_Msg() {}

func (*HubMessage_ChatCompletion) isHubMessage_Msg() {}

func (*HubMessage_Embedding) isHubMessage_Msg() {}

func (*HubMessage_BatchEmbedding) isHubMessage_Msg() {}

func (*HubMessage_Tokenize) isHubMessage_Msg() {}

func (*HubMessage_Benchmark) isHubMessage_Msg() {}

type HubLoadChatModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *rpc.LlamaChatConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	MassUrl       string                 `protobuf:"bytes,2,opt,name=mass_url,json=massUrl,proto3" json:"mass_url,omitempty"` // base URL for fetching model files from MASS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubLoadChatModel) Reset() {
	*x = HubLoadChatModel{}
	mi := &file_rpc_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubLoadChatModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubLoadChatModel) ProtoMessage() {}

func (x *HubLoadChatModel) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubLoadChatModel.ProtoReflect.Descriptor instead.
func (*HubLoadChatModel) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HubLoadChatModel) GetConfig() *rpc.LlamaChatConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HubLoadChatModel) GetMassUrl() string {
	if x != nil {
		return x.MassUrl
	}
	return ""
}

type HubLoadEmbeddingModel struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Config        *rpc.LlamaEmbeddingConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	MassUrl       string                    `protobuf:"bytes,2,opt,name=mass_url,json=massUrl,proto3" json:"mass_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubLoadEmbeddingModel) Reset() {
	*x = HubLoadEmbeddingModel{}
	mi := &file_rpc_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubLoadEmbeddingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubLoadEmbeddingModel) ProtoMessage() {}

func (x *HubLoadEmbeddingModel) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubLoadEmbeddingModel.ProtoReflect.Descriptor instead.
func (*HubLoadEmbeddingModel) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HubLoadEmbeddingModel) GetConfig() *rpc.LlamaEmbeddingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *HubLoadEmbeddingModel) GetMassUrl() string {
	if x != nil {
		return x.MassUrl
	}
	return ""
}

type HubUnloadModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubUnloadModel) Reset() {
	*x = HubUnloadModel{}
	mi := &file_rpc_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubUnloadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubUnloadModel) ProtoMessage() {}

func (x *HubUnloadModel) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubUnloadModel.ProtoReflect.Descriptor instead.
func (*HubUnloadModel) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HubUnloadModel) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type HubChatCompletion struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fingerprint   string                     `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Request       *rpc.ChatCompletionRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubChatCompletion) Reset() {
	*x = HubChatCompletion{}
	mi := &file_rpc_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubChatCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubChatCompletion) ProtoMessage() {}

func (x *HubChatCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubChatCompletion.ProtoReflect.Descriptor instead.
func (*HubChatCompletion) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *HubChatCompletion) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HubChatCompletion) GetRequest() *rpc.ChatCompletionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type HubEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Request       *rpc.EmbeddingRequest  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubEmbedding) Reset() {
	*x = HubEmbedding{}
	mi := &file_rpc_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubEmbedding) ProtoMessage() {}

func (x *HubEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubEmbedding.ProtoReflect.Descriptor instead.
func (*HubEmbedding) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *HubEmbedding) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HubEmbedding) GetRequest() *rpc.EmbeddingRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type HubBatchEmbedding struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fingerprint   string                     `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Request       *rpc.BatchEmbeddingRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubBatchEmbedding) Reset() {
	*x = HubBatchEmbedding{}
	mi := &file_rpc_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubBatchEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubBatchEmbedding) ProtoMessage() {}

func (x *HubBatchEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubBatchEmbedding.ProtoReflect.Descriptor instead.
func (*HubBatchEmbedding) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *HubBatchEmbedding) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HubBatchEmbedding) GetRequest() *rpc.BatchEmbeddingRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type HubTokenize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Request       *rpc.TokenizeRequest   `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubTokenize) Reset() {
	*x = HubTokenize{}
	mi := &file_rpc_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubTokenize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubTokenize) ProtoMessage() {}

func (x *HubTokenize) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubTokenize.ProtoReflect.Descriptor instead.
func (*HubTokenize) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *HubTokenize) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HubTokenize) GetRequest() *rpc.TokenizeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type HubBenchmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // empty = benchmark all devices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubBenchmark) Reset() {
	*x = HubBenchmark{}
	mi := &file_rpc_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubBenchmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubBenchmark) ProtoMessage() {}

func (x *HubBenchmark) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubBenchmark.ProtoReflect.Descriptor instead.
func (*HubBenchmark) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *HubBenchmark) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type AgentDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // canonical ID, e.g. "cpu:0", "gpu:0"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                           // human-readable, e.g. "NVIDIA RTX 4090"
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                           // "CPU" or "GPU"
	TotalMemoryMb int32                  `protobuf:"varint,4,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"` // total RAM/VRAM in MB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDevice) Reset() {
	*x = AgentDevice{}
	mi := &file_rpc_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDevice) ProtoMessage() {}

func (x *AgentDevice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDevice.ProtoReflect.Descriptor instead.
func (*AgentDevice) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AgentDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentDevice) GetTotalMemoryMb() int32 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

type AgentBenchmarkResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*AgentBenchmarkResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBenchmarkResponse) Reset() {
	*x = AgentBenchmarkResponse{}
	mi := &file_rpc_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBenchmarkResponse) ProtoMessage() {}

func (x *AgentBenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBenchmarkResponse.ProtoReflect.Descriptor instead.
func (*AgentBenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *AgentBenchmarkResponse) GetResults() []*AgentBenchmarkResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AgentBenchmarkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	MemoryGbs     float64                `protobuf:"fixed64,3,opt,name=memory_gbs,json=memoryGbs,proto3" json:"memory_gbs,omitempty"`
	ComputeGflops float64                `protobuf:"fixed64,5,opt,name=compute_gflops,json=computeGflops,proto3" json:"compute_gflops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBenchmarkResult) Reset() {
	*x = AgentBenchmarkResult{}
	mi := &file_rpc_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBenchmarkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBenchmarkResult) ProtoMessage() {}

func (x *AgentBenchmarkResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBenchmarkResult.ProtoReflect.Descriptor instead.
func (*AgentBenchmarkResult) Descriptor() ([]byte, []int) {
	return file_rpc_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *AgentBenchmarkResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentBenchmarkResult) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AgentBenchmarkResult) GetMemoryGbs() float64 {
	if x != nil {
		return x.MemoryGbs
	}
	return 0
}

func (x *AgentBenchmarkResult) GetComputeGflops() float64 {
	if x != nil {
		return x.ComputeGflops
	}
	return 0
}

var File_rpc_agent_agent_proto protoreflect.FileDescriptor

const file_rpc_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/agent/agent.proto\x12\rmass.v1.agent\x1a\x11rpc/service.proto\"\xd0\x01\n" +
	"\fAgentMessage\x12:\n" +
	"\bregister\x18\x01 \x01(\v2\x1c.mass.v1.agent.AgentRegisterH\x00R\bregister\x12>\n" +
	"\n" +
	"job_result\x18\x02 \x01(\v2\x1d.mass.v1.agent.AgentJobResultH\x00R\tjobResult\x12=\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1d.mass.v1.agent.AgentHeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"i\n" +
	"\rAgentRegister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\adevices\x18\x03 \x03(\v2\x1a.mass.v1.agent.AgentDeviceR\adevices\"T\n" +
	"\x0eAgentHeartbeat\x12B\n" +
	"\fdevice_stats\x18\x01 \x03(\v2\x1f.mass.v1.agent.AgentDeviceStatsR\vdeviceStats\"\xa6\x01\n" +
	"\x10AgentDeviceStats\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12$\n" +
	"\x0eused_memory_mb\x18\x02 \x01(\x05R\fusedMemoryMb\x12&\n" +
	"\x0ftotal_memory_mb\x18\x03 \x01(\x05R\rtotalMemoryMb\x12'\n" +
	"\x0futilization_pct\x18\x04 \x01(\x01R\x0eutilizationPct\"\xc8\x04\n" +
	"\x0eAgentJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12D\n" +
	"\n" +
	"load_model\x18\x02 \x01(\v2#.mass.v1.agent.AgentLoadModelResultH\x00R\tloadModel\x12E\n" +
	"\funload_model\x18\x03 \x01(\v2 .mass.v1.agent.AgentUnloadResultH\x00R\vunloadModel\x12J\n" +
	"\x0fchat_completion\x18\x04 \x01(\v2\x1f.mass.v1.ChatCompletionResponseH\x00R\x0echatCompletion\x12:\n" +
	"\tembedding\x18\x05 \x01(\v2\x1a.mass.v1.EmbeddingResponseH\x00R\tembedding\x12J\n" +
	"\x0fbatch_embedding\x18\x06 \x01(\v2\x1f.mass.v1.BatchEmbeddingResponseH\x00R\x0ebatchEmbedding\x127\n" +
	"\btokenize\x18\a \x01(\v2\x19.mass.v1.TokenizeResponseH\x00R\btokenize\x12E\n" +
	"\tbenchmark\x18\b \x01(\v2%.mass.v1.agent.AgentBenchmarkResponseH\x00R\tbenchmark\x124\n" +
	"\x05error\x18\t \x01(\v2\x1c.mass.v1.agent.AgentJobErrorH\x00R\x05errorB\b\n" +
	"\x06result\"8\n" +
	"\x14AgentLoadModelResult\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"\x13\n" +
	"\x11AgentUnloadResult\")\n" +
	"\rAgentJobError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe1\x04\n" +
	"\n" +
	"HubMessage\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12I\n" +
	"\x0fload_chat_model\x18\x02 \x01(\v2\x1f.mass.v1.agent.HubLoadChatModelH\x00R\rloadChatModel\x12X\n" +
	"\x14load_embedding_model\x18\x03 \x01(\v2$.mass.v1.agent.HubLoadEmbeddingModelH\x00R\x12loadEmbeddingModel\x12B\n" +
	"\funload_model\x18\x04 \x01(\v2\x1d.mass.v1.agent.HubUnloadModelH\x00R\vunloadModel\x12K\n" +
	"\x0fchat_completion\x18\x05 \x01(\v2 .mass.v1.agent.HubChatCompletionH\x00R\x0echatCompletion\x12;\n" +
	"\tembedding\x18\x06 \x01(\v2\x1b.mass.v1.agent.HubEmbeddingH\x00R\tembedding\x12K\n" +
	"\x0fbatch_embedding\x18\a \x01(\v2 .mass.v1.agent.HubBatchEmbeddingH\x00R\x0ebatchEmbedding\x128\n" +
	"\btokenize\x18\b \x01(\v2\x1a.mass.v1.agent.HubTokenizeH\x00R\btokenize\x12;\n" +
	"\tbenchmark\x18\t \x01(\v2\x1b.mass.v1.agent.HubBenchmarkH\x00R\tbenchmarkB\x05\n" +
	"\x03msg\"_\n" +
	"\x10HubLoadChatModel\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.mass.v1.LlamaChatConfigR\x06config\x12\x19\n" +
	"\bmass_url\x18\x02 \x01(\tR\amassUrl\"i\n" +
	"\x15HubLoadEmbeddingModel\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.mass.v1.LlamaEmbeddingConfigR\x06config\x12\x19\n" +
	"\bmass_url\x18\x02 \x01(\tR\amassUrl\"2\n" +
	"\x0eHubUnloadModel\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"o\n" +
	"\x11HubChatCompletion\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x128\n" +
	"\arequest\x18\x02 \x01(\v2\x1e.mass.v1.ChatCompletionRequestR\arequest\"e\n" +
	"\fHubEmbedding\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.mass.v1.EmbeddingRequestR\arequest\"o\n" +
	"\x11HubBatchEmbedding\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x128\n" +
	"\arequest\x18\x02 \x01(\v2\x1e.mass.v1.BatchEmbeddingRequestR\arequest\"c\n" +
	"\vHubTokenize\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x122\n" +
	"\arequest\x18\x02 \x01(\v2\x18.mass.v1.TokenizeRequestR\arequest\"+\n" +
	"\fHubBenchmark\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"m\n" +
	"\vAgentDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12&\n" +
	"\x0ftotal_memory_mb\x18\x04 \x01(\x05R\rtotalMemoryMb\"W\n" +
	"\x16AgentBenchmarkResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.mass.v1.agent.AgentBenchmarkResultR\aresults\"\x9a\x01\n" +
	"\x14AgentBenchmarkResult\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"memory_gbs\x18\x03 \x01(\x01R\tmemoryGbs\x12%\n" +
	"\x0ecompute_gflops\x18\x05 \x01(\x01R\rcomputeGflops2S\n" +
	"\bAgentHub\x12G\n" +
	"\aConnect\x12\x1b.mass.v1.agent.AgentMessage\x1a\x19.mass.v1.agent.HubMessage\"\x00(\x010\x01B2Z0github.com/chinese-room-solutions/mass/rpc/agentb\x06proto3"

var (
	file_rpc_agent_agent_proto_rawDescOnce sync.Once
	file_rpc_agent_agent_proto_rawDescData []byte
)

func file_rpc_agent_agent_proto_rawDescGZIP() []byte {
	file_rpc_agent_agent_proto_rawDescOnce.Do(func() {
		file_rpc_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_agent_agent_proto_rawDesc), len(file_rpc_agent_agent_proto_rawDesc)))
	})
	return file_rpc_agent_agent_proto_rawDescData
}

var file_rpc_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rpc_agent_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),               // 0: mass.v1.agent.AgentMessage
	(*AgentRegister)(nil),              // 1: mass.v1.agent.AgentRegister
	(*AgentHeartbeat)(nil),             // 2: mass.v1.agent.AgentHeartbeat
	(*AgentDeviceStats)(nil),           // 3: mass.v1.agent.AgentDeviceStats
	(*AgentJobResult)(nil),             // 4: mass.v1.agent.AgentJobResult
	(*AgentLoadModelResult)(nil),       // 5: mass.v1.agent.AgentLoadModelResult
	(*AgentUnloadResult)(nil),          // 6: mass.v1.agent.AgentUnloadResult
	(*AgentJobError)(nil),              // 7: mass.v1.agent.AgentJobError
	(*HubMessage)(nil),                 // 8: mass.v1.agent.HubMessage
	(*HubLoadChatModel)(nil),           // 9: mass.v1.agent.HubLoadChatModel
	(*HubLoadEmbeddingModel)(nil),      // 10: mass.v1.agent.HubLoadEmbeddingModel
	(*HubUnloadModel)(nil),             // 11: mass.v1.agent.HubUnloadModel
	(*HubChatCompletion)(nil),          // 12: mass.v1.agent.HubChatCompletion
	(*HubEmbedding)(nil),               // 13: mass.v1.agent.HubEmbedding
	(*HubBatchEmbedding)(nil),          // 14: mass.v1.agent.HubBatchEmbedding
	(*HubTokenize)(nil),                // 15: mass.v1.agent.HubTokenize
	(*HubBenchmark)(nil),               // 16: mass.v1.agent.HubBenchmark
	(*AgentDevice)(nil),                // 17: mass.v1.agent.AgentDevice
	(*AgentBenchmarkResponse)(nil),     // 18: mass.v1.agent.AgentBenchmarkResponse
	(*AgentBenchmarkResult)(nil),       // 19: mass.v1.agent.AgentBenchmarkResult
	(*rpc.ChatCompletionResponse)(nil), // 20: mass.v1.ChatCompletionResponse
	(*rpc.EmbeddingResponse)(nil),      // 21: mass.v1.EmbeddingResponse
	(*rpc.BatchEmbeddingResponse)(nil), // 22: mass.v1.BatchEmbeddingResponse
	(*rpc.TokenizeResponse)(nil),       // 23: mass.v1.TokenizeResponse
	(*rpc.LlamaChatConfig)(nil),        // 24: mass.v1.LlamaChatConfig
	(*rpc.LlamaEmbeddingConfig)(nil),   // 25: mass.v1.LlamaEmbeddingConfig
	(*rpc.ChatCompletionRequest)(nil),  // 26: mass.v1.ChatCompletionRequest
	(*rpc.EmbeddingRequest)(nil),       // 27: mass.v1.EmbeddingRequest
	(*rpc.BatchEmbeddingRequest)(nil),  // 28: mass.v1.BatchEmbeddingRequest
	(*rpc.TokenizeRequest)(nil),        // 29: mass.v1.TokenizeRequest
}
var file_rpc_agent_agent_proto_depIdxs = []int32{
	1,  // 0: mass.v1.agent.AgentMessage.register:type_name -> mass.v1.agent.AgentRegister
	4,  // 1: mass.v1.agent.AgentMessage.job_result:type_name -> mass.v1.agent.AgentJobResult
	2,  // 2: mass.v1.agent.AgentMessage.heartbeat:type_name -> mass.v1.agent.AgentHeartbeat
	17, // 3: mass.v1.agent.AgentRegister.devices:type_name -> mass.v1.agent.AgentDevice
	3,  // 4: mass.v1.agent.AgentHeartbeat.device_stats:type_name -> mass.v1.agent.AgentDeviceStats
	5,  // 5: mass.v1.agent.AgentJobResult.load_model:type_name -> mass.v1.agent.AgentLoadModelResult
	6,  // 6: mass.v1.agent.AgentJobResult.unload_model:type_name -> mass.v1.agent.AgentUnloadResult
	20, // 7: mass.v1.agent.AgentJobResult.chat_completion:type_name -> mass.v1.ChatCompletionResponse
	21, // 8: mass.v1.agent.AgentJobResult.embedding:type_name -> mass.v1.EmbeddingResponse
	22, // 9: mass.v1.agent.AgentJobResult.batch_embedding:type_name -> mass.v1.BatchEmbeddingResponse
	23, // 10: mass.v1.agent.AgentJobResult.tokenize:type_name -> mass.v1.TokenizeResponse
	18, // 11: mass.v1.agent.AgentJobResult.benchmark:type_name -> mass.v1.agent.AgentBenchmarkResponse
	7,  // 12: mass.v1.agent.AgentJobResult.error:type_name -> mass.v1.agent.AgentJobError
	9,  // 13: mass.v1.agent.HubMessage.load_chat_model:type_name -> mass.v1.agent.HubLoadChatModel
	10, // 14: mass.v1.agent.HubMessage.load_embedding_model:type_name -> mass.v1.agent.HubLoadEmbeddingModel
	11, // 15: mass.v1.agent.HubMessage.unload_model:type_name -> mass.v1.agent.HubUnloadModel
	12, // 16: mass.v1.agent.HubMessage.chat_completion:type_name -> mass.v1.agent.HubChatCompletion
	13, // 17: mass.v1.agent.HubMessage.embedding:type_name -> mass.v1.agent.HubEmbedding
	14, // 18: mass.v1.agent.HubMessage.batch_embedding:type_name -> mass.v1.agent.HubBatchEmbedding
	15, // 19: mass.v1.agent.HubMessage.tokenize:type_name -> mass.v1.agent.HubTokenize
	16, // 20: mass.v1.agent.HubMessage.benchmark:type_name -> mass.v1.agent.HubBenchmark
	24, // 21: mass.v1.agent.HubLoadChatModel.config:type_name -> mass.v1.LlamaChatConfig
	25, // 22: mass.v1.agent.HubLoadEmbeddingModel.config:type_name -> mass.v1.LlamaEmbeddingConfig
	26, // 23: mass.v1.agent.HubChatCompletion.request:type_name -> mass.v1.ChatCompletionRequest
	27, // 24: mass.v1.agent.HubEmbedding.request:type_name -> mass.v1.EmbeddingRequest
	28, // 25: mass.v1.agent.HubBatchEmbedding.request:type_name -> mass.v1.BatchEmbeddingRequest
	29, // 26: mass.v1.agent.HubTokenize.request:type_name -> mass.v1.TokenizeRequest
	19, // 27: mass.v1.agent.AgentBenchmarkResponse.results:type_name -> mass.v1.agent.AgentBenchmarkResult
	0,  // 28: mass.v1.agent.AgentHub.Connect:input_type -> mass.v1.agent.AgentMessage
	8,  // 29: mass.v1.agent.AgentHub.Connect:output_type -> mass.v1.agent.HubMessage
	29, // [29:30] is the sub-list for method output_type
	28, // [28:29] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_rpc_agent_agent_proto_init() }
func file_rpc_agent_agent_proto_init() {
	if File_rpc_agent_agent_proto != nil {
		return
	}
	file_rpc_agent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_JobResult)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_rpc_agent_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentJobResult_LoadModel)(nil),
		(*AgentJobResult_UnloadModel)(nil),
		(*AgentJobResult_ChatCompletion)(nil),
		(*AgentJobResult_Embedding)(nil),
		(*AgentJobResult_BatchEmbedding)(nil),
		(*AgentJobResult_Tokenize)(nil),
		(*AgentJobResult_Benchmark)(nil),
		(*AgentJobResult_Error)(nil),
	}
	file_rpc_agent_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*HubMessage_LoadChatModel)(nil),
		(*HubMessage_LoadEmbeddingModel)(nil),
		(*HubMessage_UnloadModel)(nil),
		(*HubMessage_ChatCompletion)(nil),
		(*HubMessage_Embedding)(nil),
		(*HubMessage_BatchEmbedding)(nil),
		(*HubMessage_Tokenize)(nil),
		(*HubMessage_Benchmark)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_agent_agent_proto_rawDesc), len(file_rpc_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_agent_agent_proto_goTypes,
		DependencyIndexes: file_rpc_agent_agent_proto_depIdxs,
		MessageInfos:      file_rpc_agent_agent_proto_msgTypes,
	}.Build()
	File_rpc_agent_agent_proto = out.File
	file_rpc_agent_agent_proto_goTypes = nil
	file_rpc_agent_agent_proto_depIdxs = nil
}
