DROP TABLE IF EXISTS runtimes;
DROP TABLE IF EXISTS device_benchmarks;
DROP TABLE IF EXISTS device_queue_state;
DROP INDEX IF EXISTS queue_results_created_at_idx;
DROP TABLE IF EXISTS queue_results;
DROP INDEX IF EXISTS goqite_queue_priority_created_idx;
DROP TRIGGER IF EXISTS goqite_updated_timestamp;
DROP TABLE IF EXISTS goqite;
DROP TABLE IF EXISTS settings;
