package resolver

import (
	"fmt"
	"os"
	"sort"

	"github.com/Masterminds/semver/v3"
	"gopkg.in/yaml.v3"
)

// LockFile represents the app.lock file that records exact resolved versions.
type LockFile struct {
	// Comment is written as a header.
	Apps map[string]LockedApp `yaml:"apps"`
}

// LockedApp is a single entry in the lock file.
type LockedApp struct {
	Version string `yaml:"version"`
	Source  string `yaml:"source"`
	SHA256  string `yaml:"sha256,omitempty"`
}

// ReadLockFile reads and parses a app.lock file. Returns an empty lock file
// if the file does not exist.
func ReadLockFile(path string) (*LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &LockFile{Apps: make(map[string]LockedApp)}, nil
		}
		return nil, fmt.Errorf("reading lock file: %w", err)
	}

	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("parsing lock file: %w", err)
	}
	if lf.Apps == nil {
		lf.Apps = make(map[string]LockedApp)
	}
	return &lf, nil
}

// WriteLockFile writes the lock file to disk.
func WriteLockFile(path string, lf *LockFile) error {
	data, err := yaml.Marshal(lf)
	if err != nil {
		return fmt.Errorf("marshalling lock file: %w", err)
	}

	header := "# Auto-generated by MASS. Do not edit.\n"
	return os.WriteFile(path, append([]byte(header), data...), 0644)
}

// LockFileFromResolved creates a LockFile from resolved apps.
func LockFileFromResolved(apps []ResolvedApp) *LockFile {
	lf := &LockFile{
		Apps: make(map[string]LockedApp, len(apps)),
	}
	for _, m := range apps {
		lf.Apps[m.Name] = LockedApp{
			Version: m.Version.String(),
			Source:  m.Source,
		}
	}
	return lf
}

// ToResolved converts lock file entries back to ResolvedApp slice.
// Apps are returned sorted by name for deterministic ordering.
func (lf *LockFile) ToResolved() ([]ResolvedApp, error) {
	names := make([]string, 0, len(lf.Apps))
	for name := range lf.Apps {
		names = append(names, name)
	}
	sort.Strings(names)

	result := make([]ResolvedApp, 0, len(names))
	for _, name := range names {
		entry := lf.Apps[name]
		v, err := semver.NewVersion(entry.Version)
		if err != nil {
			return nil, fmt.Errorf("invalid version %q for %s in lock file: %w", entry.Version, name, err)
		}
		result = append(result, ResolvedApp{
			Name:    name,
			Version: v,
			Source:  entry.Source,
		})
	}
	return result, nil
}

// IsStale returns true if the lock file doesn't cover all given dependencies
// or any locked version no longer satisfies the constraints.
func (lf *LockFile) IsStale(deps []Dependency) bool {
	for _, dep := range deps {
		locked, ok := lf.Apps[dep.Name]
		if !ok {
			return true // new dependency not in lock file
		}

		if dep.Version == "" {
			continue // no constraint, any version is fine
		}

		c, err := semver.NewConstraint(dep.Version)
		if err != nil {
			return true // unparseable constraint → re-resolve
		}
		v, err := semver.NewVersion(locked.Version)
		if err != nil {
			return true
		}
		if !c.Check(v) {
			return true // locked version no longer satisfies constraint
		}
	}
	return false
}
