// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/service.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	rpc "github.com/chinese-room-solutions/mass/rpc"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MassName is the fully-qualified name of the Mass service.
	MassName = "mass.v1.Mass"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MassChatCompletionProcedure is the fully-qualified name of the Mass's ChatCompletion RPC.
	MassChatCompletionProcedure = "/mass.v1.Mass/ChatCompletion"
	// MassBatchChatCompletionProcedure is the fully-qualified name of the Mass's BatchChatCompletion
	// RPC.
	MassBatchChatCompletionProcedure = "/mass.v1.Mass/BatchChatCompletion"
	// MassEmbeddingProcedure is the fully-qualified name of the Mass's Embedding RPC.
	MassEmbeddingProcedure = "/mass.v1.Mass/Embedding"
	// MassBatchEmbeddingProcedure is the fully-qualified name of the Mass's BatchEmbedding RPC.
	MassBatchEmbeddingProcedure = "/mass.v1.Mass/BatchEmbedding"
	// MassTokenizeProcedure is the fully-qualified name of the Mass's Tokenize RPC.
	MassTokenizeProcedure = "/mass.v1.Mass/Tokenize"
	// MassSubmitRequestProcedure is the fully-qualified name of the Mass's SubmitRequest RPC.
	MassSubmitRequestProcedure = "/mass.v1.Mass/SubmitRequest"
	// MassGetResultProcedure is the fully-qualified name of the Mass's GetResult RPC.
	MassGetResultProcedure = "/mass.v1.Mass/GetResult"
	// MassListModelsProcedure is the fully-qualified name of the Mass's ListModels RPC.
	MassListModelsProcedure = "/mass.v1.Mass/ListModels"
	// MassLoadModelProcedure is the fully-qualified name of the Mass's LoadModel RPC.
	MassLoadModelProcedure = "/mass.v1.Mass/LoadModel"
	// MassDownloadModelProcedure is the fully-qualified name of the Mass's DownloadModel RPC.
	MassDownloadModelProcedure = "/mass.v1.Mass/DownloadModel"
	// MassRunBenchmarkProcedure is the fully-qualified name of the Mass's RunBenchmark RPC.
	MassRunBenchmarkProcedure = "/mass.v1.Mass/RunBenchmark"
	// MassSetDeviceEnabledProcedure is the fully-qualified name of the Mass's SetDeviceEnabled RPC.
	MassSetDeviceEnabledProcedure = "/mass.v1.Mass/SetDeviceEnabled"
)

// MassClient is a client for the mass.v1.Mass service.
type MassClient interface {
	// --- Inference ---
	ChatCompletion(context.Context, *connect.Request[rpc.ChatCompletionRequest]) (*connect.Response[rpc.ChatCompletionResponse], error)
	BatchChatCompletion(context.Context, *connect.Request[rpc.BatchChatCompletionRequest]) (*connect.Response[rpc.BatchChatCompletionResponse], error)
	Embedding(context.Context, *connect.Request[rpc.EmbeddingRequest]) (*connect.Response[rpc.EmbeddingResponse], error)
	BatchEmbedding(context.Context, *connect.Request[rpc.BatchEmbeddingRequest]) (*connect.Response[rpc.BatchEmbeddingResponse], error)
	Tokenize(context.Context, *connect.Request[rpc.TokenizeRequest]) (*connect.Response[rpc.TokenizeResponse], error)
	// --- Async queue ---
	SubmitRequest(context.Context, *connect.Request[rpc.SubmitRequestRequest]) (*connect.Response[rpc.SubmitRequestResponse], error)
	GetResult(context.Context, *connect.Request[rpc.GetResultRequest]) (*connect.Response[rpc.GetResultResponse], error)
	// --- Model management ---
	ListModels(context.Context, *connect.Request[rpc.ListModelsRequest]) (*connect.Response[rpc.ListModelsResponse], error)
	LoadModel(context.Context, *connect.Request[rpc.LoadModelRequest]) (*connect.Response[rpc.LoadModelResponse], error)
	DownloadModel(context.Context, *connect.Request[rpc.DownloadModelRequest]) (*connect.Response[rpc.DownloadModelResponse], error)
	// --- Hardware ---
	RunBenchmark(context.Context, *connect.Request[rpc.RunBenchmarkRequest]) (*connect.Response[rpc.RunBenchmarkResponse], error)
	// --- Scheduling ---
	SetDeviceEnabled(context.Context, *connect.Request[rpc.SetDeviceEnabledRequest]) (*connect.Response[rpc.SetDeviceEnabledResponse], error)
}

// NewMassClient constructs a client for the mass.v1.Mass service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMassClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MassClient {
	baseURL = strings.TrimRight(baseURL, "/")
	massMethods := rpc.File_rpc_service_proto.Services().ByName("Mass").Methods()
	return &massClient{
		chatCompletion: connect.NewClient[rpc.ChatCompletionRequest, rpc.ChatCompletionResponse](
			httpClient,
			baseURL+MassChatCompletionProcedure,
			connect.WithSchema(massMethods.ByName("ChatCompletion")),
			connect.WithClientOptions(opts...),
		),
		batchChatCompletion: connect.NewClient[rpc.BatchChatCompletionRequest, rpc.BatchChatCompletionResponse](
			httpClient,
			baseURL+MassBatchChatCompletionProcedure,
			connect.WithSchema(massMethods.ByName("BatchChatCompletion")),
			connect.WithClientOptions(opts...),
		),
		embedding: connect.NewClient[rpc.EmbeddingRequest, rpc.EmbeddingResponse](
			httpClient,
			baseURL+MassEmbeddingProcedure,
			connect.WithSchema(massMethods.ByName("Embedding")),
			connect.WithClientOptions(opts...),
		),
		batchEmbedding: connect.NewClient[rpc.BatchEmbeddingRequest, rpc.BatchEmbeddingResponse](
			httpClient,
			baseURL+MassBatchEmbeddingProcedure,
			connect.WithSchema(massMethods.ByName("BatchEmbedding")),
			connect.WithClientOptions(opts...),
		),
		tokenize: connect.NewClient[rpc.TokenizeRequest, rpc.TokenizeResponse](
			httpClient,
			baseURL+MassTokenizeProcedure,
			connect.WithSchema(massMethods.ByName("Tokenize")),
			connect.WithClientOptions(opts...),
		),
		submitRequest: connect.NewClient[rpc.SubmitRequestRequest, rpc.SubmitRequestResponse](
			httpClient,
			baseURL+MassSubmitRequestProcedure,
			connect.WithSchema(massMethods.ByName("SubmitRequest")),
			connect.WithClientOptions(opts...),
		),
		getResult: connect.NewClient[rpc.GetResultRequest, rpc.GetResultResponse](
			httpClient,
			baseURL+MassGetResultProcedure,
			connect.WithSchema(massMethods.ByName("GetResult")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[rpc.ListModelsRequest, rpc.ListModelsResponse](
			httpClient,
			baseURL+MassListModelsProcedure,
			connect.WithSchema(massMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		loadModel: connect.NewClient[rpc.LoadModelRequest, rpc.LoadModelResponse](
			httpClient,
			baseURL+MassLoadModelProcedure,
			connect.WithSchema(massMethods.ByName("LoadModel")),
			connect.WithClientOptions(opts...),
		),
		downloadModel: connect.NewClient[rpc.DownloadModelRequest, rpc.DownloadModelResponse](
			httpClient,
			baseURL+MassDownloadModelProcedure,
			connect.WithSchema(massMethods.ByName("DownloadModel")),
			connect.WithClientOptions(opts...),
		),
		runBenchmark: connect.NewClient[rpc.RunBenchmarkRequest, rpc.RunBenchmarkResponse](
			httpClient,
			baseURL+MassRunBenchmarkProcedure,
			connect.WithSchema(massMethods.ByName("RunBenchmark")),
			connect.WithClientOptions(opts...),
		),
		setDeviceEnabled: connect.NewClient[rpc.SetDeviceEnabledRequest, rpc.SetDeviceEnabledResponse](
			httpClient,
			baseURL+MassSetDeviceEnabledProcedure,
			connect.WithSchema(massMethods.ByName("SetDeviceEnabled")),
			connect.WithClientOptions(opts...),
		),
	}
}

// massClient implements MassClient.
type massClient struct {
	chatCompletion      *connect.Client[rpc.ChatCompletionRequest, rpc.ChatCompletionResponse]
	batchChatCompletion *connect.Client[rpc.BatchChatCompletionRequest, rpc.BatchChatCompletionResponse]
	embedding           *connect.Client[rpc.EmbeddingRequest, rpc.EmbeddingResponse]
	batchEmbedding      *connect.Client[rpc.BatchEmbeddingRequest, rpc.BatchEmbeddingResponse]
	tokenize            *connect.Client[rpc.TokenizeRequest, rpc.TokenizeResponse]
	submitRequest       *connect.Client[rpc.SubmitRequestRequest, rpc.SubmitRequestResponse]
	getResult           *connect.Client[rpc.GetResultRequest, rpc.GetResultResponse]
	listModels          *connect.Client[rpc.ListModelsRequest, rpc.ListModelsResponse]
	loadModel           *connect.Client[rpc.LoadModelRequest, rpc.LoadModelResponse]
	downloadModel       *connect.Client[rpc.DownloadModelRequest, rpc.DownloadModelResponse]
	runBenchmark        *connect.Client[rpc.RunBenchmarkRequest, rpc.RunBenchmarkResponse]
	setDeviceEnabled    *connect.Client[rpc.SetDeviceEnabledRequest, rpc.SetDeviceEnabledResponse]
}

// ChatCompletion calls mass.v1.Mass.ChatCompletion.
func (c *massClient) ChatCompletion(ctx context.Context, req *connect.Request[rpc.ChatCompletionRequest]) (*connect.Response[rpc.ChatCompletionResponse], error) {
	return c.chatCompletion.CallUnary(ctx, req)
}

// BatchChatCompletion calls mass.v1.Mass.BatchChatCompletion.
func (c *massClient) BatchChatCompletion(ctx context.Context, req *connect.Request[rpc.BatchChatCompletionRequest]) (*connect.Response[rpc.BatchChatCompletionResponse], error) {
	return c.batchChatCompletion.CallUnary(ctx, req)
}

// Embedding calls mass.v1.Mass.Embedding.
func (c *massClient) Embedding(ctx context.Context, req *connect.Request[rpc.EmbeddingRequest]) (*connect.Response[rpc.EmbeddingResponse], error) {
	return c.embedding.CallUnary(ctx, req)
}

// BatchEmbedding calls mass.v1.Mass.BatchEmbedding.
func (c *massClient) BatchEmbedding(ctx context.Context, req *connect.Request[rpc.BatchEmbeddingRequest]) (*connect.Response[rpc.BatchEmbeddingResponse], error) {
	return c.batchEmbedding.CallUnary(ctx, req)
}

// Tokenize calls mass.v1.Mass.Tokenize.
func (c *massClient) Tokenize(ctx context.Context, req *connect.Request[rpc.TokenizeRequest]) (*connect.Response[rpc.TokenizeResponse], error) {
	return c.tokenize.CallUnary(ctx, req)
}

// SubmitRequest calls mass.v1.Mass.SubmitRequest.
func (c *massClient) SubmitRequest(ctx context.Context, req *connect.Request[rpc.SubmitRequestRequest]) (*connect.Response[rpc.SubmitRequestResponse], error) {
	return c.submitRequest.CallUnary(ctx, req)
}

// GetResult calls mass.v1.Mass.GetResult.
func (c *massClient) GetResult(ctx context.Context, req *connect.Request[rpc.GetResultRequest]) (*connect.Response[rpc.GetResultResponse], error) {
	return c.getResult.CallUnary(ctx, req)
}

// ListModels calls mass.v1.Mass.ListModels.
func (c *massClient) ListModels(ctx context.Context, req *connect.Request[rpc.ListModelsRequest]) (*connect.Response[rpc.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// LoadModel calls mass.v1.Mass.LoadModel.
func (c *massClient) LoadModel(ctx context.Context, req *connect.Request[rpc.LoadModelRequest]) (*connect.Response[rpc.LoadModelResponse], error) {
	return c.loadModel.CallUnary(ctx, req)
}

// DownloadModel calls mass.v1.Mass.DownloadModel.
func (c *massClient) DownloadModel(ctx context.Context, req *connect.Request[rpc.DownloadModelRequest]) (*connect.Response[rpc.DownloadModelResponse], error) {
	return c.downloadModel.CallUnary(ctx, req)
}

// RunBenchmark calls mass.v1.Mass.RunBenchmark.
func (c *massClient) RunBenchmark(ctx context.Context, req *connect.Request[rpc.RunBenchmarkRequest]) (*connect.Response[rpc.RunBenchmarkResponse], error) {
	return c.runBenchmark.CallUnary(ctx, req)
}

// SetDeviceEnabled calls mass.v1.Mass.SetDeviceEnabled.
func (c *massClient) SetDeviceEnabled(ctx context.Context, req *connect.Request[rpc.SetDeviceEnabledRequest]) (*connect.Response[rpc.SetDeviceEnabledResponse], error) {
	return c.setDeviceEnabled.CallUnary(ctx, req)
}

// MassHandler is an implementation of the mass.v1.Mass service.
type MassHandler interface {
	// --- Inference ---
	ChatCompletion(context.Context, *connect.Request[rpc.ChatCompletionRequest]) (*connect.Response[rpc.ChatCompletionResponse], error)
	BatchChatCompletion(context.Context, *connect.Request[rpc.BatchChatCompletionRequest]) (*connect.Response[rpc.BatchChatCompletionResponse], error)
	Embedding(context.Context, *connect.Request[rpc.EmbeddingRequest]) (*connect.Response[rpc.EmbeddingResponse], error)
	BatchEmbedding(context.Context, *connect.Request[rpc.BatchEmbeddingRequest]) (*connect.Response[rpc.BatchEmbeddingResponse], error)
	Tokenize(context.Context, *connect.Request[rpc.TokenizeRequest]) (*connect.Response[rpc.TokenizeResponse], error)
	// --- Async queue ---
	SubmitRequest(context.Context, *connect.Request[rpc.SubmitRequestRequest]) (*connect.Response[rpc.SubmitRequestResponse], error)
	GetResult(context.Context, *connect.Request[rpc.GetResultRequest]) (*connect.Response[rpc.GetResultResponse], error)
	// --- Model management ---
	ListModels(context.Context, *connect.Request[rpc.ListModelsRequest]) (*connect.Response[rpc.ListModelsResponse], error)
	LoadModel(context.Context, *connect.Request[rpc.LoadModelRequest]) (*connect.Response[rpc.LoadModelResponse], error)
	DownloadModel(context.Context, *connect.Request[rpc.DownloadModelRequest]) (*connect.Response[rpc.DownloadModelResponse], error)
	// --- Hardware ---
	RunBenchmark(context.Context, *connect.Request[rpc.RunBenchmarkRequest]) (*connect.Response[rpc.RunBenchmarkResponse], error)
	// --- Scheduling ---
	SetDeviceEnabled(context.Context, *connect.Request[rpc.SetDeviceEnabledRequest]) (*connect.Response[rpc.SetDeviceEnabledResponse], error)
}

// NewMassHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMassHandler(svc MassHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	massMethods := rpc.File_rpc_service_proto.Services().ByName("Mass").Methods()
	massChatCompletionHandler := connect.NewUnaryHandler(
		MassChatCompletionProcedure,
		svc.ChatCompletion,
		connect.WithSchema(massMethods.ByName("ChatCompletion")),
		connect.WithHandlerOptions(opts...),
	)
	massBatchChatCompletionHandler := connect.NewUnaryHandler(
		MassBatchChatCompletionProcedure,
		svc.BatchChatCompletion,
		connect.WithSchema(massMethods.ByName("BatchChatCompletion")),
		connect.WithHandlerOptions(opts...),
	)
	massEmbeddingHandler := connect.NewUnaryHandler(
		MassEmbeddingProcedure,
		svc.Embedding,
		connect.WithSchema(massMethods.ByName("Embedding")),
		connect.WithHandlerOptions(opts...),
	)
	massBatchEmbeddingHandler := connect.NewUnaryHandler(
		MassBatchEmbeddingProcedure,
		svc.BatchEmbedding,
		connect.WithSchema(massMethods.ByName("BatchEmbedding")),
		connect.WithHandlerOptions(opts...),
	)
	massTokenizeHandler := connect.NewUnaryHandler(
		MassTokenizeProcedure,
		svc.Tokenize,
		connect.WithSchema(massMethods.ByName("Tokenize")),
		connect.WithHandlerOptions(opts...),
	)
	massSubmitRequestHandler := connect.NewUnaryHandler(
		MassSubmitRequestProcedure,
		svc.SubmitRequest,
		connect.WithSchema(massMethods.ByName("SubmitRequest")),
		connect.WithHandlerOptions(opts...),
	)
	massGetResultHandler := connect.NewUnaryHandler(
		MassGetResultProcedure,
		svc.GetResult,
		connect.WithSchema(massMethods.ByName("GetResult")),
		connect.WithHandlerOptions(opts...),
	)
	massListModelsHandler := connect.NewUnaryHandler(
		MassListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(massMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	massLoadModelHandler := connect.NewUnaryHandler(
		MassLoadModelProcedure,
		svc.LoadModel,
		connect.WithSchema(massMethods.ByName("LoadModel")),
		connect.WithHandlerOptions(opts...),
	)
	massDownloadModelHandler := connect.NewUnaryHandler(
		MassDownloadModelProcedure,
		svc.DownloadModel,
		connect.WithSchema(massMethods.ByName("DownloadModel")),
		connect.WithHandlerOptions(opts...),
	)
	massRunBenchmarkHandler := connect.NewUnaryHandler(
		MassRunBenchmarkProcedure,
		svc.RunBenchmark,
		connect.WithSchema(massMethods.ByName("RunBenchmark")),
		connect.WithHandlerOptions(opts...),
	)
	massSetDeviceEnabledHandler := connect.NewUnaryHandler(
		MassSetDeviceEnabledProcedure,
		svc.SetDeviceEnabled,
		connect.WithSchema(massMethods.ByName("SetDeviceEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mass.v1.Mass/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MassChatCompletionProcedure:
			massChatCompletionHandler.ServeHTTP(w, r)
		case MassBatchChatCompletionProcedure:
			massBatchChatCompletionHandler.ServeHTTP(w, r)
		case MassEmbeddingProcedure:
			massEmbeddingHandler.ServeHTTP(w, r)
		case MassBatchEmbeddingProcedure:
			massBatchEmbeddingHandler.ServeHTTP(w, r)
		case MassTokenizeProcedure:
			massTokenizeHandler.ServeHTTP(w, r)
		case MassSubmitRequestProcedure:
			massSubmitRequestHandler.ServeHTTP(w, r)
		case MassGetResultProcedure:
			massGetResultHandler.ServeHTTP(w, r)
		case MassListModelsProcedure:
			massListModelsHandler.ServeHTTP(w, r)
		case MassLoadModelProcedure:
			massLoadModelHandler.ServeHTTP(w, r)
		case MassDownloadModelProcedure:
			massDownloadModelHandler.ServeHTTP(w, r)
		case MassRunBenchmarkProcedure:
			massRunBenchmarkHandler.ServeHTTP(w, r)
		case MassSetDeviceEnabledProcedure:
			massSetDeviceEnabledHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMassHandler returns CodeUnimplemented from all methods.
type UnimplementedMassHandler struct{}

func (UnimplementedMassHandler) ChatCompletion(context.Context, *connect.Request[rpc.ChatCompletionRequest]) (*connect.Response[rpc.ChatCompletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.ChatCompletion is not implemented"))
}

func (UnimplementedMassHandler) BatchChatCompletion(context.Context, *connect.Request[rpc.BatchChatCompletionRequest]) (*connect.Response[rpc.BatchChatCompletionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.BatchChatCompletion is not implemented"))
}

func (UnimplementedMassHandler) Embedding(context.Context, *connect.Request[rpc.EmbeddingRequest]) (*connect.Response[rpc.EmbeddingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.Embedding is not implemented"))
}

func (UnimplementedMassHandler) BatchEmbedding(context.Context, *connect.Request[rpc.BatchEmbeddingRequest]) (*connect.Response[rpc.BatchEmbeddingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.BatchEmbedding is not implemented"))
}

func (UnimplementedMassHandler) Tokenize(context.Context, *connect.Request[rpc.TokenizeRequest]) (*connect.Response[rpc.TokenizeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.Tokenize is not implemented"))
}

func (UnimplementedMassHandler) SubmitRequest(context.Context, *connect.Request[rpc.SubmitRequestRequest]) (*connect.Response[rpc.SubmitRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.SubmitRequest is not implemented"))
}

func (UnimplementedMassHandler) GetResult(context.Context, *connect.Request[rpc.GetResultRequest]) (*connect.Response[rpc.GetResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.GetResult is not implemented"))
}

func (UnimplementedMassHandler) ListModels(context.Context, *connect.Request[rpc.ListModelsRequest]) (*connect.Response[rpc.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.ListModels is not implemented"))
}

func (UnimplementedMassHandler) LoadModel(context.Context, *connect.Request[rpc.LoadModelRequest]) (*connect.Response[rpc.LoadModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.LoadModel is not implemented"))
}

func (UnimplementedMassHandler) DownloadModel(context.Context, *connect.Request[rpc.DownloadModelRequest]) (*connect.Response[rpc.DownloadModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.DownloadModel is not implemented"))
}

func (UnimplementedMassHandler) RunBenchmark(context.Context, *connect.Request[rpc.RunBenchmarkRequest]) (*connect.Response[rpc.RunBenchmarkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.RunBenchmark is not implemented"))
}

func (UnimplementedMassHandler) SetDeviceEnabled(context.Context, *connect.Request[rpc.SetDeviceEnabledRequest]) (*connect.Response[rpc.SetDeviceEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mass.v1.Mass.SetDeviceEnabled is not implemented"))
}
